-- CORRECTED STEP 3: Migrate existing data using ACTUAL existing columns
-- =====================================================

-- First, let's see what we're working with
SELECT COUNT(*) as total_records,
       COUNT(CASE WHEN business_id IS NULL THEN 1 END) as founder_records,
       COUNT(CASE WHEN business_id IS NOT NULL THEN 1 END) as business_records
FROM business_insights_snapshots;

-- Migrate founder insights (records without business_id)
INSERT INTO founder_insights (
    user_id,
    snapshot_year,
    submitted_date,
    gender,
    age_range,
    years_entrepreneurial,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_role,
    founder_story,
    founder_motivation_array,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    created_date,
    updated_at
)
SELECT 
    user_id,
    snapshot_year,
    submitted_date,
    gender,
    age_range,
    years_entrepreneurial,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_role,
    founder_story,
    founder_motivation_array,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    created_date,
    updated_at
FROM business_insights_snapshots 
WHERE business_id IS NULL;

-- Migrate business insights (records with business_id) - using ALL existing business columns
INSERT INTO business_insights (
    business_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    community_impact_areas,
    collaboration_interest,
    entrepreneurial_background,
    businesses_founded,
    industry,
    family_entrepreneurial_background,
    mentorship_access,
    mentorship_offering,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    revenue_band,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    support_needed_next,
    current_support_sources,
    goals_details,
    expansion_plans,
    open_to_future_contact,
    founder_motivation_array,
    goals_next_12_months_array,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    angel_investor_interest,
    investor_capacity,
    revenue_streams,
    financial_challenges,
    barriers_to_mentorship,
    investment_exploration,
    team_size,
    created_date,
    updated_at
)
SELECT 
    business_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    community_impact_areas,
    collaboration_interest,
    entrepreneurial_background,
    businesses_founded,
    industry,
    family_entrepreneurial_background,
    mentorship_access,
    mentorship_offering,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    revenue_band,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    support_needed_next,
    current_support_sources,
    goals_details,
    expansion_plans,
    open_to_future_contact,
    founder_motivation_array,
    goals_next_12_months_array,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    angel_investor_interest,
    investor_capacity,
    revenue_streams,
    financial_challenges,
    barriers_to_mentorship,
    investment_exploration,
    team_size,
    created_date,
    updated_at
FROM business_insights_snapshots 
WHERE business_id IS NOT NULL;

-- Verify the migration
SELECT 
    'Founder Insights' as table_name,
    COUNT(*) as migrated_count,
    COUNT(DISTINCT user_id) as unique_users
FROM founder_insights

UNION ALL

SELECT 
    'Business Insights' as table_name,
    COUNT(*) as migrated_count,
    COUNT(DISTINCT business_id) as unique_users
FROM business_insights;
