-- Migrate data from business_insights_snapshots to the new separated tables
-- This will fix the Insights page by moving the existing data to the correct tables

-- First, let's see what's in the old table
SELECT '=== OLD TABLE DATA ===' as info;
SELECT COUNT(*) as total_records FROM business_insights_snapshots;

-- Migrate founder data to founder_insights table
INSERT INTO founder_insights (
    id, 
    user_id, 
    snapshot_year, 
    submitted_date,
    gender,
    age_range,
    years_entrepreneurial,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_role,
    founder_story,
    founder_motivation_array,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    goals_details,
    goals_next_12_months_array,
    created_date,
    updated_at
)
SELECT 
    id,
    user_id,
    snapshot_year,
    submitted_date,
    gender,
    age_range,
    years_entrepreneurial,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_role,
    founder_story,
    founder_motivation_array,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    goals_details,
    goals_next_12_months_array,
    created_date,
    updated_at
FROM business_insights_snapshots 
WHERE user_id IS NOT NULL 
  AND (gender IS NOT NULL OR age_range IS NOT NULL OR years_entrepreneurial IS NOT NULL);

-- Migrate business data to business_insights table
INSERT INTO business_insights (
    id,
    business_id,
    user_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    team_size,
    revenue_band,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    revenue_streams,
    financial_challenges,
    investment_exploration,
    community_impact_areas,
    support_needed_next,
    current_support_sources,
    expansion_plans,
    industry,
    created_date,
    updated_at
)
SELECT 
    id,
    business_id,
    user_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    team_size,
    revenue_band,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    revenue_streams,
    financial_challenges,
    investment_exploration,
    community_impact_areas,
    support_needed_next,
    current_support_sources,
    expansion_plans,
    industry,
    created_date,
    updated_at
FROM business_insights_snapshots;

-- Verify the migration
SELECT '=== AFTER MIGRATION ===' as info;
SELECT 'founder_insights' as table_name, COUNT(*) as record_count FROM founder_insights
UNION ALL
SELECT 'business_insights' as table_name, COUNT(*) as record_count FROM business_insights;
