-- STEP 3: Re-run migration now that all columns exist
-- =====================================================

-- First, clear any existing data to start fresh
TRUNCATE TABLE business_insights;

-- Now migrate all business insights with complete field list
INSERT INTO business_insights (
    business_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    team_size,
    revenue_band,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    revenue_streams,
    financial_challenges,
    investment_exploration,
    community_impact_areas,
    support_needed_next,
    current_support_sources,
    expansion_plans,
    industry,
    -- Founder fields
    gender,
    age_range,
    years_entrepreneurial,
    founder_role,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_story,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    goals_details,
    goals_next_12_months_array,
    founder_motivation_array,
    created_date,
    updated_at
)
SELECT 
    business_id,
    snapshot_year,
    submitted_date,
    year_started,
    problem_solved,
    team_size_band,
    business_model,
    family_involvement,
    customer_region,
    sales_channels,
    import_export_status,
    import_countries,
    export_countries,
    business_stage,
    top_challenges,
    hiring_intentions,
    business_operating_status,
    business_age,
    business_registered,
    employs_anyone,
    employs_family_community,
    team_size,
    revenue_band,
    current_funding_source,
    funding_amount_needed,
    funding_purpose,
    investment_stage,
    revenue_streams,
    financial_challenges,
    investment_exploration,
    community_impact_areas,
    support_needed_next,
    current_support_sources,
    expansion_plans,
    industry,
    -- Founder fields
    gender,
    age_range,
    years_entrepreneurial,
    founder_role,
    entrepreneurial_background,
    businesses_founded,
    family_entrepreneurial_background,
    founder_story,
    pacific_identity,
    based_in_country,
    based_in_city,
    serves_pacific_communities,
    culture_influences_business,
    culture_influence_details,
    family_community_responsibilities_affect_business,
    responsibilities_impact_details,
    mentorship_access,
    mentorship_offering,
    barriers_to_mentorship,
    angel_investor_interest,
    investor_capacity,
    collaboration_interest,
    open_to_future_contact,
    goals_details,
    goals_next_12_months_array,
    founder_motivation_array,
    created_date,
    updated_at
FROM business_insights_snapshots 
WHERE business_id IS NOT NULL;

-- Verify the complete migration
SELECT 
    COUNT(*) as total_migrated,
    COUNT(DISTINCT business_id) as unique_businesses,
    COUNT(CASE WHEN gender IS NOT NULL THEN 1 END) as has_gender,
    COUNT(CASE WHEN age_range IS NOT NULL THEN 1 END) as has_age_range,
    COUNT(CASE WHEN years_entrepreneurial IS NOT NULL THEN 1 END) as has_years_entrepreneurial
FROM business_insights;
