// Unified Constants for Pacific Discovery Network
// Single source of truth for all countries, languages, and cultural identities

export const LANGUAGES = [
  // Pacific Languages
  { value: 'english', label: 'English' },
  { value: 'french', label: 'French' },
  { value: 'maori', label: 'Māori (New Zealand)' },
  { value: 'samoan', label: 'Samoan' },
  { value: 'tongan', label: 'Tongan' },
  { value: 'fijian', label: 'Fijian' },
  { value: 'cook-islands-maori', label: 'Cook Islands Māori' },
  { value: 'niuean', label: 'Niuean' },
  { value: 'tokelauan', label: 'Tokelauan' },
  { value: 'tuvaluan', label: 'Tuvaluan' },
  { value: 'kiribati', label: 'Kiribati' },
  { value: 'marshallese', label: 'Marshallese' },
  { value: 'palauan', label: 'Palauan' },
  { value: 'chamorro', label: 'Chamorro' },
  { value: 'tahitian', label: 'Tahitian' },
  { value: 'hawaiian', label: 'Hawaiian' },
  { value: 'papua-new-guinea', label: 'Papua New Guinea Languages' },
  { value: 'solomon-islands', label: 'Solomon Islands Languages' },
  { value: 'vanuatuan', label: 'Vanuatuan Languages' },
  { value: 'new-caledonian', label: 'New Caledonian Languages' },
  { value: 'wallisian', label: 'Wallisian' },
  { value: 'micronesian', label: 'Micronesian Languages' },
  { value: 'guamanian', label: 'Guamanian' },
  { value: 'northern-mariana', label: 'Northern Mariana Islands Languages' },
  { value: 'american-samoan', label: 'American Samoan' },
  
  // Major World Languages
  { value: 'mandarin', label: 'Mandarin Chinese' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'arabic', label: 'Arabic' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'bengali', label: 'Bengali' },
  { value: 'russian', label: 'Russian' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'punjabi', label: 'Punjabi' },
  { value: 'german', label: 'German' },
  { value: 'javanese', label: 'Javanese' },
  { value: 'korean', label: 'Korean' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'italian', label: 'Italian' },
  { value: 'vietnamese', label: 'Vietnamese' },
  { value: 'thai', label: 'Thai' },
  { value: 'tagalog', label: 'Tagalog (Filipino)' },
  { value: 'urdu', label: 'Urdu' },
  { value: 'indonesian', label: 'Indonesian' },
  { value: 'persian', label: 'Persian (Farsi)' },
  { value: 'dutch', label: 'Dutch' },
  { value: 'greek', label: 'Greek' },
  { value: 'polish', label: 'Polish' },
  { value: 'ukrainian', label: 'Ukrainian' },
  { value: 'romanian', label: 'Romanian' },
  { value: 'czech', label: 'Czech' },
  { value: 'hungarian', label: 'Hungarian' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'danish', label: 'Danish' },
  { value: 'norwegian', label: 'Norwegian' },
  { value: 'finnish', label: 'Finnish' },
  { value: 'hebrew', label: 'Hebrew' },
  { value: 'other', label: 'Other' }
];

export const COUNTRIES = [
  // Pacific Region
  { value: 'american-samoa', label: 'American Samoa' },
  { value: 'australia', label: 'Australia' },
  { value: 'cook-islands', label: 'Cook Islands' },
  { value: 'fiji', label: 'Fiji' },
  { value: 'french-polynesia', label: 'French Polynesia' },
  { value: 'guam', label: 'Guam' },
  { value: 'kiribati', label: 'Kiribati' },
  { value: 'marshall-islands', label: 'Marshall Islands' },
  { value: 'micronesia', label: 'Micronesia' },
  { value: 'nauru', label: 'Nauru' },
  { value: 'new-caledonia', label: 'New Caledonia' },
  { value: 'new-zealand', label: 'New Zealand' },
  { value: 'niue', label: 'Niue' },
  { value: 'northern-mariana-islands', label: 'Northern Mariana Islands' },
  { value: 'palau', label: 'Palau' },
  { value: 'papua-new-guinea', label: 'Papua New Guinea' },
  { value: 'samoa', label: 'Samoa' },
  { value: 'solomon-islands', label: 'Solomon Islands' },
  { value: 'tokelau', label: 'Tokelau' },
  { value: 'tonga', label: 'Tonga' },
  { value: 'tuvalu', label: 'Tuvalu' },
  { value: 'vanuatu', label: 'Vanuatu' },
  { value: 'wallis-futuna', label: 'Wallis and Futuna' },
  { value: 'hawaii', label: 'Hawaii' },

  // Global Countries (A-Z)
  { value: 'afghanistan', label: 'Afghanistan' },
  { value: 'albania', label: 'Albania' },
  { value: 'algeria', label: 'Algeria' },
  { value: 'andorra', label: 'Andorra' },
  { value: 'angola', label: 'Angola' },
  { value: 'argentina', label: 'Argentina' },
  { value: 'armenia', label: 'Armenia' },
  { value: 'austria', label: 'Austria' },
  { value: 'azerbaijan', label: 'Azerbaijan' },
  { value: 'bahamas', label: 'Bahamas' },
  { value: 'bangladesh', label: 'Bangladesh' },
  { value: 'barbados', label: 'Barbados' },
  { value: 'belarus', label: 'Belarus' },
  { value: 'belgium', label: 'Belgium' },
  { value: 'belize', label: 'Belize' },
  { value: 'benin', label: 'Benin' },
  { value: 'bhutan', label: 'Bhutan' },
  { value: 'bolivia', label: 'Bolivia' },
  { value: 'bosnia-and-herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'botswana', label: 'Botswana' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'bulgaria', label: 'Bulgaria' },
  { value: 'burkina-faso', label: 'Burkina Faso' },
  { value: 'burundi', label: 'Burundi' },
  { value: 'cambodia', label: 'Cambodia' },
  { value: 'cameroon', label: 'Cameroon' },
  { value: 'canada', label: 'Canada' },
  { value: 'central-african-republic', label: 'Central African Republic' },
  { value: 'chad', label: 'Chad' },
  { value: 'chile', label: 'Chile' },
  { value: 'china', label: 'China' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'comoros', label: 'Comoros' },
  { value: 'congo', label: 'Congo' },
  { value: 'costa-rica', label: 'Costa Rica' },
  { value: 'croatia', label: 'Croatia' },
  { value: 'cuba', label: 'Cuba' },
  { value: 'cyprus', label: 'Cyprus' },
  { value: 'czech-republic', label: 'Czech Republic' },
  { value: 'denmark', label: 'Denmark' },
  { value: 'djibouti', label: 'Djibouti' },
  { value: 'dominican-republic', label: 'Dominican Republic' },
  { value: 'ecuador', label: 'Ecuador' },
  { value: 'egypt', label: 'Egypt' },
  { value: 'el-salvador', label: 'El Salvador' },
  { value: 'estonia', label: 'Estonia' },
  { value: 'ethiopia', label: 'Ethiopia' },
  { value: 'finland', label: 'Finland' },
  { value: 'france', label: 'France' },
  { value: 'gabon', label: 'Gabon' },
  { value: 'gambia', label: 'Gambia' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'germany', label: 'Germany' },
  { value: 'ghana', label: 'Ghana' },
  { value: 'greece', label: 'Greece' },
  { value: 'grenada', label: 'Grenada' },
  { value: 'guatemala', label: 'Guatemala' },
  { value: 'guinea', label: 'Guinea' },
  { value: 'guinea-bissau', label: 'Guinea-Bissau' },
  { value: 'guyana', label: 'Guyana' },
  { value: 'haiti', label: 'Haiti' },
  { value: 'honduras', label: 'Honduras' },
  { value: 'hungary', label: 'Hungary' },
  { value: 'iceland', label: 'Iceland' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'iran', label: 'Iran' },
  { value: 'iraq', label: 'Iraq' },
  { value: 'ireland', label: 'Ireland' },
  { value: 'israel', label: 'Israel' },
  { value: 'italy', label: 'Italy' },
  { value: 'jamaica', label: 'Jamaica' },
  { value: 'japan', label: 'Japan' },
  { value: 'jordan', label: 'Jordan' },
  { value: 'kazakhstan', label: 'Kazakhstan' },
  { value: 'kenya', label: 'Kenya' },
  { value: 'kosovo', label: 'Kosovo' },
  { value: 'kuwait', label: 'Kuwait' },
  { value: 'kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'laos', label: 'Laos' },
  { value: 'latvia', label: 'Latvia' },
  { value: 'lebanon', label: 'Lebanon' },
  { value: 'lesotho', label: 'Lesotho' },
  { value: 'liberia', label: 'Liberia' },
  { value: 'libya', label: 'Libya' },
  { value: 'liechtenstein', label: 'Liechtenstein' },
  { value: 'lithuania', label: 'Lithuania' },
  { value: 'luxembourg', label: 'Luxembourg' },
  { value: 'madagascar', label: 'Madagascar' },
  { value: 'malawi', label: 'Malawi' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'maldives', label: 'Maldives' },
  { value: 'mali', label: 'Mali' },
  { value: 'malta', label: 'Malta' },
  { value: 'mauritania', label: 'Mauritania' },
  { value: 'mauritius', label: 'Mauritius' },
  { value: 'mexico', label: 'Mexico' },
  { value: 'moldova', label: 'Moldova' },
  { value: 'monaco', label: 'Monaco' },
  { value: 'mongolia', label: 'Mongolia' },
  { value: 'montenegro', label: 'Montenegro' },
  { value: 'morocco', label: 'Morocco' },
  { value: 'mozambique', label: 'Mozambique' },
  { value: 'myanmar', label: 'Myanmar' },
  { value: 'namibia', label: 'Namibia' },
  { value: 'nepal', label: 'Nepal' },
  { value: 'netherlands', label: 'Netherlands' },
  { value: 'nigeria', label: 'Nigeria' },
  { value: 'north-macedonia', label: 'North Macedonia' },
  { value: 'norway', label: 'Norway' },
  { value: 'oman', label: 'Oman' },
  { value: 'pakistan', label: 'Pakistan' },
  { value: 'panama', label: 'Panama' },
  { value: 'paraguay', label: 'Paraguay' },
  { value: 'peru', label: 'Peru' },
  { value: 'philippines', label: 'Philippines' },
  { value: 'poland', label: 'Poland' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'qatar', label: 'Qatar' },
  { value: 'romania', label: 'Romania' },
  { value: 'russia', label: 'Russia' },
  { value: 'rwanda', label: 'Rwanda' },
  { value: 'saudi-arabia', label: 'Saudi Arabia' },
  { value: 'senegal', label: 'Senegal' },
  { value: 'serbia', label: 'Serbia' },
  { value: 'sierra-leone', label: 'Sierra Leone' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'slovakia', label: 'Slovakia' },
  { value: 'slovenia', label: 'Slovenia' },
  { value: 'south-africa', label: 'South Africa' },
  { value: 'south-korea', label: 'South Korea' },
  { value: 'spain', label: 'Spain' },
  { value: 'sri-lanka', label: 'Sri Lanka' },
  { value: 'sudan', label: 'Sudan' },
  { value: 'sweden', label: 'Sweden' },
  { value: 'switzerland', label: 'Switzerland' },
  { value: 'syria', label: 'Syria' },
  { value: 'taiwan', label: 'Taiwan' },
  { value: 'tajikistan', label: 'Tajikistan' },
  { value: 'tanzania', label: 'Tanzania' },
  { value: 'thailand', label: 'Thailand' },
  { value: 'tunisia', label: 'Tunisia' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'turkmenistan', label: 'Turkmenistan' },
  { value: 'uganda', label: 'Uganda' },
  { value: 'ukraine', label: 'Ukraine' },
  { value: 'united-arab-emirates', label: 'United Arab Emirates' },
  { value: 'united-kingdom', label: 'United Kingdom' },
  { value: 'united-states', label: 'United States' },
  { value: 'uruguay', label: 'Uruguay' },
  { value: 'uzbekistan', label: 'Uzbekistan' },
  { value: 'venezuela', label: 'Venezuela' },
  { value: 'vietnam', label: 'Vietnam' },
  { value: 'yemen', label: 'Yemen' },
  { value: 'zambia', label: 'Zambia' },
  { value: 'zimbabwe', label: 'Zimbabwe' }
];

// Mapping from display identity to flag country
export const DISPLAY_TO_FLAG_COUNTRY = {
  "New Zealand Maori": "New Zealand",
  "Cook Islands Maori": "Cook Islands",
  "I-Kiribati": "Kiribati",
  "Marshallese": "Marshall Islands",
  "Chuukese": "Micronesia",
  "Pohnpeian": "Micronesia",
  "Yapese": "Micronesia",
  "Kosraean": "Micronesia",
  "Nauruan": "Nauru",
  "Niuean": "Niue",
  "Palauan": "Palau",
  "Papuan": "Papua New Guinea",
  "Samoan": "Samoa",
  "Tongan": "Tonga",
  "Tuvaluan": "Tuvalu",
  "Ni-Vanuatu": "Vanuatu",
  "Fijian": "Fiji",
  "Indo-Fijian": "Fiji",
  "Rotuman": "Fiji",
  "Australia - Torres Strait Islander": "Australia",
  "Australia - Aboriginal": "Australia",
};

// Mapping from country to ISO flag codes
export const COUNTRY_FLAG_CODES = {
  "American Samoa": "AS",
  "Australia": "AU",
  "Cook Islands": "CK",
  "Fiji": "FJ",
  "French Polynesia": "PF",
  "Guam": "GU",
  "Kiribati": "KI",
  "Marshall Islands": "MH",
  "Micronesia": "FM",
  "Nauru": "NR",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  "Niue": "NU",
  "Northern Mariana Islands": "MP",
  "Palau": "PW",
  "Papua New Guinea": "PG",
  "Samoa": "WS",
  "Solomon Islands": "SB",
  "Tokelau": "TK",
  "Tonga": "TO",
  "Tuvalu": "TV",
  "Vanuatu": "VU",
  "Wallis and Futuna": "WF",
  // Additional countries for global support
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Argentina": "AR",
  "Armenia": "AM",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo": "CG",
  "Costa Rica": "CR",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "East Timor": "TL",
  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Ethiopia": "ET",
  "Federated States of Micronesia": "FM",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Honduras": "HN",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Korea (North)": "KP",
  "Korea (South)": "KR",
  "Kosovo": "XK",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Palestine": "PS",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Swaziland": "SZ",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Vatican City": "VA",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",
};

// Cultural identities for dropdown (Pacific identities + all countries)
export const CULTURAL_IDENTITIES = Array.from(
  new Set([
    // Pacific-specific cultural identities
    "Australia - Torres Strait Islander",
    "Australia - Aboriginal", 
    "Cook Islands Maori",
    "Fijian",
    "Indo-Fijian",
    "Rotuman",
    "I-Kiribati",
    "Marshallese",
    "Chuukese",
    "Pohnpeian",
    "Yapese",
    "Kosraean",
    "Nauruan",
    "New Zealand Maori",
    "Niuean",
    "Palauan",
    "Papuan",
    "Samoan",
    "Tongan",
    "Tuvaluan",
    "Ni-Vanuatu",
    
    // All countries (for users who identify with their country)
    ...COUNTRIES.map((c) => c.label),
  ])
);

// Mapping of Pacific cultural identities to their corresponding countries
const IDENTITY_TO_COUNTRY = {
  'New Zealand Maori': 'New Zealand',
  'Cook Islands Maori': 'Cook Islands',
  'I-Kiribati': 'Kiribati',
  'Marshallese': 'Marshall Islands',
  'Chuukese': 'Micronesia',
  'Pohnpeian': 'Micronesia',
  'Yapese': 'Micronesia',
  'Kosraean': 'Micronesia',
  'Nauruan': 'Nauru',
  'Niuean': 'Niue',
  'Palauan': 'Palau',
  'Papuan': 'Papua New Guinea',
  'Samoan': 'Samoa',
  'Tongan': 'Tonga',
  'Tuvaluan': 'Tuvalu',
  'Ni-Vanuatu': 'Vanuatu',
  'Fijian': 'Fiji',
  'Indo-Fijian': 'Fiji',
  'Rotuman': 'Fiji',
  'Solomon Islands': 'Solomon Islands',
  'Australia - Torres Strait Islander': 'Australia',
  'Australia - Aboriginal': 'Australia',
};

// Helper function to get country from cultural identity
export const getCountryFromCulturalIdentity = (identity) => {
  if (!identity) return null;

  const cleaned = String(identity).trim().replace(/^"(.*)"$/, '$1');

  // Check Pacific identity mappings first
  if (IDENTITY_TO_COUNTRY[cleaned]) {
    return IDENTITY_TO_COUNTRY[cleaned];
  }

  // Check if it's a country label
  const country = COUNTRIES.find((c) => c.label === cleaned);
  if (country) {
    return country.label;
  }

  return null;
};

// Helper function to get cultural identities by country
export const getCulturalIdentitiesByCountry = (country) => {
  if (!country) return [];

  return CULTURAL_IDENTITIES.filter(
    (identity) => getCountryFromCulturalIdentity(identity) === country
  );
};

export const INDUSTRIES = [
  { value: 'agriculture', label: 'Agriculture/Fishing' },
  { value: 'arts_crafts', label: 'Arts & Crafts' },
  { value: 'beauty_personal_care', label: 'Beauty & Personal Care' },
  { value: 'books_publishing', label: 'Books & Publishing' },
  { value: 'clothing_fashion', label: 'Clothing & Fashion' },
  { value: 'coaching_business_personal', label: 'Coaching (Business & Personal)' },
  { value: 'construction_trade', label: 'Construction & Trade' },
  { value: 'digital_it_technology', label: 'Digital & IT Technology' },
  { value: 'education_training', label: 'Education & Training' },
  { value: 'fashion_accessories', label: 'Fashion Accessories' },
  { value: 'finance_insurance', label: 'Finance & Insurance' },
  { value: 'food_beverage', label: 'Food & Beverage' },
  { value: 'health_wellness', label: 'Health & Wellness' },
  { value: 'hospitality', label: 'Hospitality' },
  { value: 'import_export', label: 'Import/Export' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'media_entertainment', label: 'Media & Entertainment' },
  { value: 'nonprofit', label: 'Nonprofit' },
  { value: 'professional_services', label: 'Professional Services' },
  { value: 'retail', label: 'Retail' },
  { value: 'technology', label: 'Technology' },
  { value: 'transport_logistics', label: 'Transport & Logistics' },
  { value: 'travel_tourism', label: 'Travel & Tourism' },
  { value: 'other', label: 'Other' }
];

// Business constants
export const BUSINESS_STATUS = {
  ACTIVE: 'active',
  PENDING: 'pending',
  REJECTED: 'rejected',
};

// Business status options for dropdowns/find operations
export const BUSINESS_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'pending', label: 'Pending' },
  { value: 'rejected', label: 'Rejected' },
];

export const SUBSCRIPTION_TIER = {
  VAKA: 'vaka',
  MANA: 'mana', 
  MOANA: 'moana',
};

// Stripe price lookup keys (must match Stripe Dashboard)
export const STRIPE_PRICE_LOOKUP_KEYS = {
  MANA: 'price_mana',
  MOANA: 'price_moana',
};

export const getTierDisplayName = (tier) => {
  const displayNames = {
    'vaka': 'Vaka',
    'mana': 'Mana',
    'moana': 'Moana',
  };
  return displayNames[tier] || tier;
};

export const BUSINESS_SOURCE = {
  USER: 'user',
  ADMIN: 'admin',
  IMPORT: 'import',
  CLAIM: 'claim',
};

export const TEAM_SIZE_BAND = [
  { value: 'solo', label: 'Just me (1 person)' },
  { value: '2-5', label: '2-5 people' },
  { value: '6-10', label: '6-10 people' },
  { value: '11-50', label: '11-50 people' },
  { value: '51+', label: '51+ people' },
];

export const BUSINESS_STAGE = [
  { value: 'idea', label: 'Idea/Concept' },
  { value: 'startup', label: 'Startup/Launch' },
  { value: 'growth', label: 'Growth/Scaling' },
  { value: 'mature', label: 'Mature/Established' },
];

export const IMPORT_EXPORT_STATUS = {
  NONE: 'none',
  IMPORT_ONLY: 'import_only',
  EXPORT_ONLY: 'export_only',
  BOTH: 'both',
};

// Business operations constants
export const BUSINESS_OPERATING_STATUS = [
  { value: 'planning', label: 'Planning' },
  { value: 'operating', label: 'Operating' },
  { value: 'paused', label: 'Paused' },
  { value: 'closed', label: 'Closed' },
];

export const SALES_CHANNELS = [
  { value: 'online', label: 'Online/E-commerce' },
  { value: 'retail', label: 'Retail Store' },
  { value: 'market', label: 'Market/Stall' },
  { value: 'direct', label: 'Direct to Customer' },
  { value: 'wholesale', label: 'Wholesale' },
  { value: 'export', label: 'Export' },
  { value: 'services', label: 'Services' },
  { value: 'other', label: 'Other' },
];

// Financial & Investment constants
export const FUNDING_SOURCES = [
  { value: 'personal-savings', label: 'Personal savings' },
  { value: 'family-friends', label: 'Family and friends' },
  { value: 'bank-loan', label: 'Bank loan' },
  { value: 'government-grant', label: 'Government grant' },
  { value: 'angel-investor', label: 'Angel investor' },
  { value: 'venture-capital', label: 'Venture capital' },
  { value: 'crowdfunding', label: 'Crowdfunding' },
  { value: 'revenue-profit', label: 'Revenue/profit reinvested' },
  { value: 'no-funding', label: 'No external funding' },
  { value: 'other', label: 'Other' },
];

export const FUNDING_AMOUNTS = [
  { value: '0-5k', label: 'Under $5,000' },
  { value: '5k-10k', label: '$5,000 - $10,000' },
  { value: '10k-25k', label: '$10,000 - $25,000' },
  { value: '25k-50k', label: '$25,000 - $50,000' },
  { value: '50k-100k', label: '$50,000 - $100,000' },
  { value: '100k-250k', label: '$100,000 - $250,000' },
  { value: '250k-500k', label: '$250,000 - $500,000' },
  { value: '500k-1m', label: '$500,000 - $1,000,000' },
  { value: '1m+', label: '$1,000,000+' },
  { value: 'not-sure', label: 'Not sure yet' },
];

export const FUNDING_PURPOSES = [
  { value: 'product-development', label: 'Product development/R&D' },
  { value: 'marketing-sales', label: 'Marketing and sales' },
  { value: 'hiring-staff', label: 'Hiring staff' },
  { value: 'equipment-assets', label: 'Equipment and assets' },
  { value: 'operations-expansion', label: 'Operations expansion' },
  { value: 'working-capital', label: 'Working capital' },
  { value: 'debt-consolidation', label: 'Debt consolidation' },
  { value: 'international-expansion', label: 'International expansion' },
  { value: 'technology-upgrade', label: 'Technology upgrade' },
  { value: 'other', label: 'Other' },
];

export const INVESTMENT_STAGES = [
  { value: 'pre-seed', label: 'Pre-seed (idea stage)' },
  { value: 'seed', label: 'Seed (early development)' },
  { value: 'early-stage', label: 'Early stage (product launched)' },
  { value: 'growth-stage', label: 'Growth stage (scaling)' },
  { value: 'established', label: 'Established (mature business)' },
  { value: 'not-seeking', label: 'Not seeking investment' },
];

export const INVESTMENT_EXPLORATION = [
  { value: 'actively-seeking', label: 'Actively seeking investment now' },
  { value: 'exploring-options', label: 'Exploring investment options' },
  { value: 'considering-future', label: 'Considering for future (6+ months)' },
  { value: 'researching-only', label: 'Just researching, not ready to engage' },
  { value: 'not-interested', label: 'Not interested in investment' },
  { value: 'not-sure', label: 'Not sure about investment' },
];

export const INVESTMENT_TIMELINE = [
  { value: 'immediate', label: 'Immediate (next 1-3 months)' },
  { value: 'short-term', label: 'Short term (3-6 months)' },
  { value: 'medium-term', label: 'Medium term (6-12 months)' },
  { value: 'long-term', label: 'Long term (1-2 years)' },
  { value: 'beyond-2-years', label: 'Beyond 2 years' },
  { value: 'no-timeline', label: 'No specific timeline' },
];

export const ANGEL_INVESTOR_INTEREST = [
  { value: 'actively-investing', label: 'Actively investing in Pacific Discovery Network businesses' },
  { value: 'considering-future', label: 'Considering investing in future (6+ months)' },
  { value: 'exploring-options', label: 'Exploring angel investing options' },
  { value: 'interested-learning', label: 'Interested in learning more first' },
  { value: 'not-interested', label: 'Not interested in investing' },
  { value: 'already-investing', label: 'Already investing in other businesses' },
];

export const INVESTOR_CAPACITY = [
  { value: 'under-5k', label: 'Under $5,000 per investment' },
  { value: '5k-25k', label: '$5,000 - $25,000 per investment' },
  { value: '25k-100k', label: '$25,000 - $100,000 per investment' },
  { value: '100k-500k', label: '$100,000 - $500,000 per investment' },
  { value: '500k+', label: '$500,000+ per investment' },
  { value: 'varies', label: 'Varies by opportunity' },
  { value: 'prefer-not-to-say', label: 'Prefer not to say' },
];

export const REVENUE_STREAMS = [
  { value: 'product-sales', label: 'Product sales' },
  { value: 'service-fees', label: 'Service fees' },
  { value: 'subscription', label: 'Subscription/recurring' },
  { value: 'consulting', label: 'Consulting/advisory' },
  { value: 'licensing', label: 'Licensing royalties' },
  { value: 'advertising', label: 'Advertising/sponsorship' },
  { value: 'commission', label: 'Commission/referral' },
  { value: 'rental', label: 'Rental/leasing' },
  { value: 'other', label: 'Other' },
];

// Founder Insights constants
export const FOUNDER_MOTIVATIONS = [
  { value: 'financial_independence', label: 'Financial independence' },
  { value: 'family_opportunities', label: 'Creating opportunities for family' },
  { value: 'serving_community', label: 'Serving community' },
  { value: 'preserving_culture', label: 'Preserving culture' },
  { value: 'solving_problem', label: 'Solving a problem' },
  { value: 'building_wealth', label: 'Building wealth' },
  { value: 'creative_freedom', label: 'Creative freedom' },
  { value: 'legacy_building', label: 'Legacy building' },
  { value: 'other', label: 'Other' },
];

export const BUSINESS_CHALLENGES = [
  { value: 'access_funding', label: 'Access to funding' },
  { value: 'finding_customers', label: 'Finding customers' },
  { value: 'pricing_sales', label: 'Pricing and sales' },
  { value: 'marketing_visibility', label: 'Marketing and visibility' },
  { value: 'time_workload', label: 'Time and workload' },
  { value: 'family_community_obligations', label: 'Balancing family/community obligations' },
  { value: 'admin_compliance', label: 'Admin and compliance' },
  { value: 'hiring_staffing', label: 'Hiring and staffing' },
  { value: 'digital_tools', label: 'Digital tools and systems' },
  { value: 'confidence_growth', label: 'Confidence in growth planning' },
  { value: 'shipping_costs', label: 'Shipping or supply costs' },
  { value: 'small_market', label: 'Small market size' },
  { value: 'limited_support', label: 'Limited trusted support' },
  { value: 'cultural_barriers', label: 'Cultural barriers in business' },
  { value: 'geographic_isolation', label: 'Geographic isolation' },
  { value: 'other', label: 'Other' },
];

export const SUPPORT_NEEDS = [
  { value: 'funding_grants', label: 'Funding or grants' },
  { value: 'mentoring', label: 'Mentoring' },
  { value: 'marketing_support', label: 'Marketing support' },
  { value: 'digital_support', label: 'Website or digital support' },
  { value: 'bookkeeping_help', label: 'Bookkeeping or finance help' },
  { value: 'legal_help', label: 'Legal or compliance help' },
  { value: 'business_planning', label: 'Business planning' },
  { value: 'export_scaling', label: 'Export or scaling support' },
  { value: 'networking', label: 'Networking opportunities' },
  { value: 'training_programs', label: 'Training programs' },
  { value: 'community_connections', label: 'Community connections' },
  { value: 'confidence_accountability', label: 'Confidence and accountability' },
  { value: 'other', label: 'Other' },
];

export const GOALS_NEXT_12_MONTHS = [
  { value: 'grow_revenue', label: 'Grow revenue' },
  { value: 'get_customers', label: 'Get more customers' },
  { value: 'strengthen_systems', label: 'Strengthen systems and processes' },
  { value: 'improve_digital', label: 'Improve digital presence' },
  { value: 'launch_products', label: 'Launch new products or services' },
  { value: 'hire_staff', label: 'Hire staff' },
  { value: 'expand_markets', label: 'Expand to new markets' },
  { value: 'secure_funding', label: 'Secure funding' },
  { value: 'build_visibility', label: 'Build brand visibility' },
  { value: 'community_impact', label: 'Create more community impact' },
  { value: 'other', label: 'Other' },
];

export const COMMUNITY_IMPACT_AREAS = [
  { value: 'family_income', label: 'Creates income for family' },
  { value: 'creates_jobs', label: 'Creates jobs' },
  { value: 'pacific_visibility', label: 'Supports Pacific visibility' },
  { value: 'preserves_culture', label: 'Preserves culture' },
  { value: 'community_role_model', label: 'Role model for youth' },
  { value: 'knowledge_sharing', label: 'Knowledge sharing' },
  { value: 'local_economy', label: 'Strengthens local economy' },
  { value: 'other', label: 'Other' }
];

export const FAMILY_RESPONSIBILITIES = [
  { value: 'children', label: 'Children (under 18)' },
  { value: 'eldercare', label: 'Elderly parents/grandparents care' },
  { value: 'extended_family', label: 'Extended family support' },
  { value: 'community_leadership', label: 'Community leadership roles' },
  { value: 'cultural_obligations', label: 'Cultural/religious obligations' },
  { value: 'family_business', label: 'Family business duties' },
  { value: 'caregiving', label: 'Other caregiving responsibilities' },
  { value: 'none', label: 'No additional family commitments' }
];

export const GENDER_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'non_binary', label: 'Non-binary' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' }
];

export const AGE_RANGES = [
  { value: '18-24', label: '18-24' },
  { value: '25-34', label: '25-34' },
  { value: '35-44', label: '35-44' },
  { value: '45-54', label: '45-54' },
  { value: '55-64', label: '55-64' },
  { value: '65+', label: '65+' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' }
];

// Helper functions to get display names from values
export const getCountryDisplayName = (value) => {
  const country = COUNTRIES.find(c => c.value === value);
  return country ? country.label : value;
};

export const getIndustryDisplayName = (value) => {
  const industry = INDUSTRIES.find(i => i.value === value);
  return industry ? industry.label : value;
};
