import { PresentationDeck } from "@/lib/presentations/types";

export const investorOverviewDeck: PresentationDeck = {
  slug: "investor-overview",
  title: "Investor Overview",
  description: "Investor-facing presentation for Pacific Discovery Network.",
  audience: "Investors",
  status: "live",
  theme: "pdn-investor",
  createdAt: "2026-03-19",
  updatedAt: "2026-03-19",
  slides: [
    {
      id: "cover",
      type: "cover",
      title: "Pacific Discovery Network",
      subtitle: "The digital discovery and business tools platform for Pacific-owned businesses",
      tagline: "Helping Pacific businesses become more visible, credible, and digitally equipped",
      statusBadge: "Production-ready platform",
      contact: "contact@pacificdiscoverynetwork.com · pacificdiscoverynetwork.com",
      footer: "Investor Overview · March 2026",
    },
    {
      id: "opportunity",
      type: "stats",
      eyebrow: "The Opportunity",
      title: "Pacific businesses remain underserved in the digital economy",
      subtitle:
        "Pacific-owned businesses across New Zealand, Australia, and the wider Pacific often operate with limited digital visibility, fragmented discovery channels, and limited access to affordable business tools.",
      stats: [
        { label: "Addressable Market", value: "75,000+" },
        { label: "Market Opportunity", value: "$2.3B" },
        { label: "Without Strong Digital Presence", value: "80%" },
      ],
      bullets: [
        "Limited digital visibility across the Pacific business ecosystem",
        "No modern discovery-first platform dedicated to Pacific-owned businesses",
        "Small businesses face fragmented and expensive digital tools",
      ],
      closingLine: "We see a clear opportunity to build a trusted, culturally relevant platform that improves discoverability and equips businesses with practical digital tools.",
    },
    {
      id: "problem",
      type: "bullets",
      eyebrow: "The Problem",
      title: "Discovery is fragmented, tools are expensive, and mainstream platforms are not built for this market",
      bullets: [
        "Many Pacific businesses rely heavily on word of mouth and social media alone",
        "There is no dominant, modern platform dedicated to discovering Pacific-owned businesses",
        "Existing business tools are often fragmented, expensive, or designed for larger markets",
        "Visibility, trust, and digital credibility remain major barriers to growth",
        "Mainstream platforms do not reflect Pacific context, community dynamics, or business realities",
      ],
      closingLine: "The result is a market with real economic potential, but limited digital infrastructure built specifically to serve it.",
    },
    {
      id: "solution",
      type: "three-column",
      eyebrow: "The Solution",
      title: "Pacific Discovery Network combines visibility, trust, and business tools in one platform",
      subtitle: "We are building a focused business ecosystem designed to help Pacific businesses show up professionally online and access practical tools at an affordable price point.",
      columns: [
        {
          title: "Business Directory & Profiles",
          items: [
            "Rich public business listings",
            "Photos, descriptions, contact details",
            "Search and filter by industry and location",
            "Stronger visibility and discoverability",
          ],
        },
        {
          title: "Trust & Credibility",
          items: [
            "Verification workflows",
            "Structured business profiles",
            "Professional digital presentation",
            "Brand presence that feels credible to customers and partners",
          ],
        },
        {
          title: "Business Tools",
          items: [
            "Invoice generator",
            "Email signature generator",
            "QR code generator",
            "Premium features designed to support day-to-day business operations",
          ],
        },
      ],
      closingLine: "Instead of asking small businesses to piece together multiple disconnected tools, we provide a more focused and accessible platform built around their needs.",
    },
    {
      id: "product",
      type: "bullets",
      eyebrow: "Product Overview",
      title: "A production-ready platform with clear utility from day one",
      subtitle: "Pacific Discovery Network is already structured as a working software platform with core functionality in place and a clear pathway for feature expansion.",
      sections: [
        {
          title: "Directory experience",
          items: [
            "Business discovery",
            "Search and filtering",
            "Public business pages",
            "Category and geography-based browsing",
          ],
        },
        {
          title: "Premium business tools",
          items: [
            "Branded invoice generation",
            "Professional email signatures",
            "QR code creation",
            "Profile enhancement and premium presentation features",
          ],
        },
        {
          title: "Admin and platform operations",
          items: [
            "Authentication and profile management",
            "Subscription handling via Stripe",
            "Admin workflows for verification and oversight",
            "Scalable architecture for future product extensions",
          ],
        },
      ],
      techStack: "Current stack: Next.js, TypeScript, Tailwind, Supabase, Stripe, Vercel",
    },
    {
      id: "why-now",
      type: "bullets",
      eyebrow: "Why Now",
      title: "Market timing favours a focused, culturally relevant digital platform",
      bullets: [
        "More small businesses now expect to be discovered online",
        "Digital credibility increasingly influences trust and conversion",
        "Pacific entrepreneurs remain underserved by mainstream business platforms",
        "Lightweight SaaS infrastructure makes it possible to serve niche markets efficiently",
        "There is a growing opportunity to build category leadership before the space becomes crowded",
      ],
      closingLine: "This is a timely opportunity to establish a strong brand and trusted platform in a market that remains underbuilt.",
    },
    {
      id: "market",
      type: "table",
      eyebrow: "Market Opportunity",
      title: "We are targeting a focused but meaningful regional market",
      subtitle: "Our initial market includes Pacific-owned businesses across New Zealand, Australia, and the Pacific, with future expansion potential into diaspora and institutional channels.",
      table: {
        headers: ["Segment", "Estimated Businesses"],
        rows: [
          ["Pacific Island businesses", "~50,000"],
          ["New Zealand Pacific businesses", "~15,000"],
          ["Australian Pacific businesses", "~10,000"],
          ["Total Addressable Market", "75,000+"],
        ],
      },
      bullets: [
        "Initial focus is on small to medium-sized businesses",
        "Target industries include retail, food, services, hospitality, consulting, and creative sectors",
        "The longer-term opportunity extends into sponsorships, partnerships, governments, and ecosystem infrastructure",
      ],
      closingLine: "We are not trying to serve every business category globally. We are focused on becoming the trusted platform within a defined and underserved market.",
    },
    {
      id: "business-model",
      type: "tiers",
      eyebrow: "Business Model",
      title: "Subscription-led revenue with room for expansion",
      subtitle: "The initial model is designed to balance affordability for small businesses with recurring revenue and clear upgrade pathways.",
      tiers: [
        {
          name: "Free",
          price: "$0",
          features: [
            "Basic listing",
            "Entry-level visibility",
            "Platform access",
          ],
        },
        {
          name: "Mana",
          price: "$4.99/month",
          features: [
            "Enhanced profile",
            "Core business tools",
            "Verification-related value",
            "Strong step-up option for early adopters",
          ],
        },
        {
          name: "Moana",
          price: "$29/month",
          features: [
            "Full feature access",
            "Premium profile presence",
            "Advanced functionality",
            "Higher-value subscriber tier",
          ],
        },
      ],
      futureRevenue: [
        "Featured placements",
        "Advanced analytics",
        "White-label or institutional offerings",
        "Partnership and ecosystem revenue",
        "Premium support and expansion tools",
      ],
      closingLine: "The model starts simple, but is intentionally structured to support stronger monetisation over time.",
    },
    {
      id: "traction",
      type: "bullets",
      eyebrow: "Current Status",
      title: "The platform is built, live, and positioned for growth",
      bullets: [
        "Production-ready platform is already in place",
        "Core user flows and business profile infrastructure are operational",
        "Stripe subscription capability is integrated",
        "Core business tools are already part of the platform experience",
        "Admin workflows support verification and platform management",
        "Positioned to shift from build phase into structured growth phase",
      ],
      credibilityNote: "Avoid claiming large traction numbers here unless you have them. Keep this slide honest and strong.",
      closingLine: "We are no longer pitching a concept alone. We have a functioning platform and a clear next phase: distribution, adoption, and market penetration.",
    },
    {
      id: "go-to-market",
      type: "three-column",
      eyebrow: "Go-To-Market",
      title: "Community-led growth first, then performance-led scale",
      subtitle: "Our go-to-market approach is designed for trust-first adoption in a relationship-driven market.",
      columns: [
        {
          title: "Community and association partnerships",
          items: [
            "Pacific business associations",
            "Cultural and business events",
            "Community organisations",
            "Founder-led trust building",
          ],
        },
        {
          title: "Content and visibility",
          items: [
            "Founder story and mission-led brand positioning",
            "Business success stories",
            "Educational business content",
            "SEO and niche discoverability",
          ],
        },
        {
          title: "Paid acquisition and referrals",
          items: [
            "Targeted Meta campaigns",
            "Search-driven acquisition",
            "Referral incentives",
            "Conversion-focused offers for early adopters",
          ],
        },
      ],
      closingLine: "We expect early growth to come from founder-led trust, community access, and partnerships, before heavier reliance on paid acquisition.",
    },
    {
      id: "financials",
      type: "financial-table",
      eyebrow: "Financial Projections",
      title: "A subscription model with a path to meaningful recurring revenue",
      subtitle: "These figures are internal projections based on our current pricing model, subscriber assumptions, and growth strategy. They should be treated as directional targets rather than guaranteed outcomes.",
      table: {
        headers: ["Year", "Subscribers", "Annual Revenue"],
        rows: [
          ["Year 1", "1,000", "$204K"],
          ["Year 2", "2,500", "$510K"],
          ["Year 3", "5,000", "$1.02M"],
        ],
      },
      sideStats: [
        { label: "ARPU target", value: "~$17/month" },
        { label: "Break-even target", value: "around Month 18" },
        { label: "Year 3 market penetration target", value: "~6.7%" },
      ],
      closingLine: "The model is attractive because software margins improve materially once customer acquisition and retention systems begin working efficiently.",
    },
    {
      id: "use-of-funds",
      type: "allocation",
      eyebrow: "Use of Funds",
      title: "Capital will be used to accelerate product maturity and market penetration",
      ask: "Seeking: $250,000",
      allocations: [
        {
          category: "Product Development",
          percentage: 40,
          amount: "$100K",
          items: [
            "Mobile experience",
            "Advanced analytics",
            "Integrations",
            "Stronger premium tooling",
          ],
        },
        {
          category: "Marketing & Sales",
          percentage: 35,
          amount: "$87.5K",
          items: [
            "Community partnerships",
            "Digital acquisition",
            "Content and conversion systems",
            "Launch and growth campaigns",
          ],
        },
        {
          category: "Team Expansion",
          percentage: 20,
          amount: "$50K",
          items: [
            "Development support",
            "Marketing support",
            "Customer support / community operations",
          ],
        },
        {
          category: "Operations",
          percentage: 5,
          amount: "$12.5K",
          items: [
            "Legal",
            "Compliance",
            "Infrastructure support",
            "Contingency",
          ],
        },
      ],
      closingLine: "The capital is intended to move the company from a production-ready platform into a structured growth phase with stronger adoption and revenue traction.",
    },
    {
      id: "vision",
      type: "bullets",
      eyebrow: "Future Vision",
      title: "From directory to digital backbone for Pacific business",
      subtitle: "The long-term opportunity is larger than listings alone. Pacific Discovery Network can evolve into a broader digital infrastructure layer for visibility, tools, trust, partnerships, and business intelligence.",
      bullets: [
        "Broader Pacific and diaspora market expansion",
        "Institutional and government partnerships",
        "White-label ecosystem tools",
        "Premium business enablement services",
        "Aggregated business insights and economic data infrastructure",
      ],
      closingLine: "Our ambition is to become the most trusted digital platform connecting Pacific businesses to customers, opportunities, and growth.",
    },
    {
      id: "ask",
      type: "ask",
      eyebrow: "The Ask",
      title: "Raising $250,000 to accelerate growth",
      mainPoints: [
        "Raise: $250,000",
        "Indicative valuation: $2M pre-money",
        "Indicative equity offered: 11.1%",
        "Use: growth, product expansion, team capacity, market activation",
      ],
      investorRationale: [
        "A focused niche with limited direct competition",
        "A culturally relevant platform with strong differentiation",
        "A founder-led business with a clear product already in market",
        "A scalable software model with recurring revenue potential",
      ],
      closingLine: "We are looking for aligned capital that understands both the commercial opportunity and the broader long-term value of building trusted Pacific business infrastructure.",
    },
    {
      id: "closing",
      type: "closing",
      title: "Building the platform Pacific businesses deserve",
      subtitle: "Pacific Discovery Network is designed to help Pacific businesses become more discoverable, more credible, and better equipped for the digital economy.",
      cta: "Thank you",
      contact: {
        name: "Jasmin Benioni",
        title: "Founder, Pacific Discovery Network",
        email: "contact@pacificdiscoverynetwork.com",
        website: "pacificdiscoverynetwork.com",
      },
      finalLine: "Visibility. Credibility. Growth. Built for Pacific business.",
    },
  ],
};

export type InvestorDeck = PresentationDeck;
