import { PresentationDeck } from "@/lib/presentations/types";

export const investorOverviewDeck: PresentationDeck = {
  slug: "investor-overview",
  title: "Investor Overview",
  description: "Investor-facing presentation for Pacific Discovery Network.",
  audience: "Investors",
  status: "live",
  theme: "pdn-investor",
  createdAt: "2026-03-19",
  updatedAt: "2026-03-19",
  slides: [
    {
      id: "cover",
      type: "cover",
      title: "Pacific Discovery Network",
      subtitle: "The discovery platform and data hub for Pacific-owned businesses",
      tagline: "Building visibility, trust, and ecosystem intelligence for Pacific business",
      statusBadge: "Production-ready platform",
      contact: "contact@pacificdiscoverynetwork.com · pacificdiscoverynetwork.com",
      footer: "Investor Overview · March 2026",
    },
    {
      id: "opportunity",
      type: "stats",
      eyebrow: "The Opportunity",
      title: "Pacific businesses are under-discovered and under-documented",
      subtitle:
        "Pacific-owned businesses face two gaps: limited digital discoverability and fragmented data collection. The absence of consistent Pacific business data itself demonstrates the market need.",
      stats: [
        { label: "Validated NZ Pacific Businesses", value: "3,555" },
        { label: "Pacific Heritage in Australia", value: "337K" },
        { label: "French Pacific Active Companies", value: "86K" },
      ],
      bullets: [
        "Pacific-owned business counts are inconsistent across regions, highlighting a data gap",
        "No modern discovery platform dedicated to Pacific-owned businesses",
        "Limited visibility for Pacific Island producers seeking global trade partners",
      ],
      closingLine: "The fragmented data landscape is not a weakness—it's evidence of the opportunity to build both a discovery layer and a Pacific business intelligence hub.",
    },
    {
      id: "problem",
      type: "bullets",
      eyebrow: "The Problem",
      title: "Fragmented discoverability, weak data infrastructure, and limited trade visibility",
      bullets: [
        "Pacific businesses rely on word-of-mouth and fragmented social media presence",
        "No centralized platform for discovering Pacific-owned businesses across regions",
        "Pacific business data is inconsistently collected and poorly structured",
        "Limited visibility for Pacific Island producers in global trade and export markets",
        "No clear way to identify businesses seeking investment, mentorship, or collaboration",
        "Mainstream platforms do not capture Pacific-specific business contexts and needs",
      ],
      closingLine: "The absence of structured Pacific business data creates both a discovery gap and an intelligence gap that limits ecosystem growth.",
    },
    {
      id: "solution",
      type: "three-column",
      eyebrow: "The Solution",
      title: "Discovery platform, data hub, and practical tools for Pacific business",
      subtitle: "We're building a two-fold mission: help people discover Pacific businesses, and create structured Pacific business intelligence for ecosystem growth.",
      columns: [
        {
          title: "Discovery Platform",
          items: [
            "Searchable Pacific business directory",
            "Industry and location filtering",
            "Professional business profiles",
            "Global trade and export visibility",
          ],
        },
        {
          title: "Pacific Data Hub",
          items: [
            "Structured business ecosystem data",
            "Founder demographics and business stage",
            "Investment and collaboration signals",
            "Export readiness and product categories",
          ],
        },
        {
          title: "Practical Tools",
          items: [
            "Verification workflows",
            "Business document generators",
            "Professional presentation tools",
            "Affordable subscription access",
          ],
        },
      ],
      closingLine: "Pacific Discovery Network becomes both the place where Pacific businesses are found, and where Pacific business ecosystem intelligence becomes structured and useful.",
    },
    {
      id: "product",
      type: "bullets",
      eyebrow: "Product Overview",
      title: "Production-ready platform with discovery, data capture, and trade visibility",
      subtitle: "Pacific Discovery Network combines public business discovery with structured ecosystem data capture and practical business tools.",
      sections: [
        {
          title: "Public discovery platform",
          items: [
            "Searchable Pacific business directory",
            "Industry and location filtering",
            "Professional business profiles",
            "Export and trade product visibility",
          ],
        },
        {
          title: "Ecosystem data capture",
          items: [
            "Founder demographics and business stage",
            "Investment readiness and collaboration intent",
            "Export readiness and product categories",
            "Mentorship and partnership signals",
          ],
        },
        {
          title: "Business tools & operations",
          items: [
            "Verification workflows and trust signals",
            "Document generators and professional tools",
            "Subscription management and user access",
            "Scalable architecture for regional expansion",
          ],
        },
      ],
      techStack: "Current stack: Next.js, JavaScript, Tailwind, Supabase, Stripe, Netlify",
    },
    {
      id: "why-now",
      type: "bullets",
      eyebrow: "Why Now",
      title: "Market timing favours a focused, culturally relevant digital platform",
      bullets: [
        "More small businesses now expect to be discovered online",
        "Digital credibility increasingly influences trust and conversion",
        "Pacific entrepreneurs remain underserved by mainstream business platforms",
        "Lightweight SaaS infrastructure makes it possible to serve niche markets efficiently",
        "There is a growing opportunity to build category leadership before the space becomes crowded",
      ],
      closingLine: "This is a timely opportunity to establish a strong brand and trusted platform in a market that remains underbuilt.",
    },
    {
      id: "market",
      type: "table",
      eyebrow: "Market Opportunity",
      title: "Validated core market with staged regional expansion",
      subtitle: "We start with strong evidence from New Zealand, directional signals from Australia and French Pacific, and clear expansion pathways across the Pacific region.",
      table: {
        headers: ["Market Segment", "Evidence Type"],
        rows: [
          ["NZ Pacific Businesses", "3,555 validated"],
          ["Pacific Heritage Australia", "337,000 population"],
          ["French Pacific Companies", "86,216 active"],
        ],
      },
      bullets: [
        "New Zealand provides validated Pacific-owned business counts as our core market foundation",
        "Australia and French Pacific show meaningful business activity signals, though Pacific-owned breakdowns are inconsistent",
        "Pacific Island nations represent key expansion markets for trade and export visibility",
        "The data inconsistency itself demonstrates the need for better Pacific business intelligence",
      ],
      closingLine: "Current evidence indicates a meaningful underserved market, with the absence of consistent Pacific business data highlighting the opportunity for better infrastructure.",
    },
    {
      id: "business-model",
      type: "tiers",
      eyebrow: "Business Model",
      title: "Subscription-led revenue with room for expansion",
      subtitle: "The initial model is designed to balance affordability for small businesses with recurring revenue and clear upgrade pathways.",
      tiers: [
        {
          name: "Free",
          price: "$0",
          features: [
            "Basic listing",
            "Entry-level visibility",
            "Platform access",
          ],
        },
        {
          name: "Mana",
          price: "$4.99/month",
          features: [
            "Enhanced profile",
            "Core business tools",
            "Verification-related value",
            "Strong step-up option for early adopters",
          ],
        },
        {
          name: "Moana",
          price: "$29/month",
          features: [
            "Full feature access",
            "Premium profile presence",
            "Advanced functionality",
            "Higher-value subscriber tier",
          ],
        },
      ],
      futureRevenue: [
        "Featured placements",
        "Advanced analytics",
        "White-label or institutional offerings",
        "Partnership and ecosystem revenue",
        "Premium support and expansion tools",
      ],
      closingLine: "The model starts simple, but is intentionally structured to support stronger monetisation over time.",
    },
    {
      id: "traction",
      type: "bullets",
      eyebrow: "Current Status",
      title: "The platform is built, live, and positioned for growth",
      bullets: [
        "Production-ready platform is already in place",
        "Core user flows and business profile infrastructure are operational",
        "Stripe subscription capability is integrated",
        "Core business tools are already part of the platform experience",
        "Admin workflows support verification and platform management",
        "Positioned to shift from build phase into structured growth phase",
      ],
      credibilityNote: "Avoid claiming large traction numbers here unless you have them. Keep this slide honest and strong.",
      closingLine: "We are no longer pitching a concept alone. We have a functioning platform and a clear next phase: distribution, adoption, and market penetration.",
    },
    {
      id: "go-to-market",
      type: "three-column",
      eyebrow: "Go-To-Market",
      title: "Community-led growth first, then performance-led scale",
      subtitle: "Our go-to-market approach is designed for trust-first adoption in a relationship-driven market.",
      columns: [
        {
          title: "Community and association partnerships",
          items: [
            "Pacific business associations",
            "Cultural and business events",
            "Community organisations",
            "Founder-led trust building",
          ],
        },
        {
          title: "Content and visibility",
          items: [
            "Founder story and mission-led brand positioning",
            "Business success stories",
            "Educational business content",
            "SEO and niche discoverability",
          ],
        },
        {
          title: "Paid acquisition and referrals",
          items: [
            "Targeted Meta campaigns",
            "Search-driven acquisition",
            "Referral incentives",
            "Conversion-focused offers for early adopters",
          ],
        },
      ],
      closingLine: "We expect early growth to come from founder-led trust, community access, and partnerships, before heavier reliance on paid acquisition.",
    },
    {
      id: "financials",
      type: "financial-table",
      eyebrow: "Financial Projections",
      title: "Subscription revenue with 60/40 Mana-Moana pricing mix",
      subtitle: "Directional subscription-only projections based on current tier pricing (Mana: $4.99/month, Moana: $29/month). Excludes future premium services and data revenue layers.",
      table: {
        headers: ["Year", "Subscribers", "Annual Revenue"],
        rows: [
          ["Year 1", "1,000", "~$175K"],
          ["Year 2", "2,500", "~$438K"],
          ["Year 3", "5,000", "~$876K"],
        ],
      },
      sideStats: [
        { label: "Blended ARPU", value: "$14.59/month" },
        { label: "Mana tier (60%)", value: "$4.99/month" },
        { label: "Moana tier (40%)", value: "$29/month" },
      ],
      closingLine: "These subscription-only forecasts provide a foundation for future revenue layers from premium placements, ecosystem insights, and data services.",
    },
    {
      id: "use-of-funds",
      type: "allocation",
      eyebrow: "Use of Funds",
      title: "Capital will be used to accelerate product maturity and market penetration",
      ask: "Seeking: $250,000",
      allocations: [
        {
          category: "Product Development",
          percentage: 40,
          amount: "$100K",
          items: [
            "Mobile experience",
            "Analytics & integrations",
            "Premium tools",
          ],
        },
        {
          category: "Marketing & Sales",
          percentage: 35,
          amount: "$87.5K",
          items: [
            "Community partnerships",
            "Digital acquisition",
            "Growth campaigns",
          ],
        },
        {
          category: "Team Expansion",
          percentage: 20,
          amount: "$50K",
          items: [
            "Development support",
            "Marketing & customer support",
          ],
        },
        {
          category: "Operations",
          percentage: 5,
          amount: "$12.5K",
          items: [
            "Legal & compliance",
            "Infrastructure",
          ],
        },
      ],
      closingLine: "The capital is intended to move the company from a production-ready platform into a structured growth phase with stronger adoption and revenue traction.",
    },
    {
      id: "vision",
      type: "bullets",
      eyebrow: "Future Vision",
      title: "From discovery platform to Pacific business infrastructure",
      subtitle: "Pacific Discovery Network evolves from a discovery tool into the trusted data and intelligence layer for the entire Pacific business ecosystem.",
      bullets: [
        "Pacific discovery infrastructure across New Zealand, Australia, and Pacific Islands",
        "Structured Pacific business data hub for governments, investors, and partners",
        "Trade and export visibility for Pacific producers (taro, kava, noni, artisan goods)",
        "White-label ecosystem tools for Pacific business organizations",
        "Pacific data sovereignty and ecosystem intelligence services",
      ],
      closingLine: "We become both where Pacific businesses are discovered globally, and where Pacific business ecosystem intelligence becomes structured, visible, and actionable.",
    },
    {
      id: "ask",
      type: "ask",
      eyebrow: "The Ask",
      title: "Raising $250,000 to accelerate growth",
      mainPoints: [
        "Raise: $250,000",
        "Indicative valuation: $2M pre-money",
        "Indicative equity offered: 11.1%",
        "Use: growth, product expansion, team capacity, market activation",
      ],
      investorRationale: [
        "A focused niche with limited direct competition",
        "A culturally relevant platform with strong differentiation",
        "A founder-led business with a clear product already in market",
        "A scalable software model with recurring revenue potential",
      ],
      closingLine: "We are looking for aligned capital that understands both the commercial opportunity and the broader long-term value of building trusted Pacific business infrastructure.",
    },
    {
      id: "closing",
      type: "closing",
      title: "Building Pacific discovery and data infrastructure",
      subtitle: "Pacific Discovery Network is creating the trusted platform where Pacific businesses are discovered globally, and where Pacific business ecosystem intelligence becomes structured and useful.",
      cta: "Thank you",
      contact: {
        name: "Jasmin Benioni",
        title: "Founder, Pacific Discovery Network",
        email: "contact@pacificdiscoverynetwork.com",
        website: "pacificdiscoverynetwork.com",
      },
      finalLine: "Discovery. Data. Sovereignty. Built for Pacific business.",
    },
  ],
};

export type InvestorDeck = PresentationDeck;
